Projet de Gestion de Tarifs des vols: OD Class Reference
OD Class Reference
Classe représentant un itinéraire Origine-Destination avec des tarifs associés.
#include <OD.hpp>
Public Member Functions
OD (const std::string &ori, const std::string &dest)
Constructeur de la classe OD.
void afficher () const
Affiche la liste des tarifs associés à l'OD pour une meilleur visualisation.
void ajouterTarif (const Tarif &tarif)
Ajoute un tarif à la liste en respectant certaines règles :
Tarif obtenirTarifNetMinimum () const
Retourne le tarif net minimum parmi la liste des tarifs.
Tarif obtenirTarifNetMaximum () const
Retourne le tarif net maximum parmi la liste des tarifs.
double calculerMoyenneNet () const
Calcule la moyenne des tarifs nets.
Public Attributes
std::string origine
Origine du trajet.
std::string destination
Destination du trajet.
Private Attributes
std::vector< Tarif > tarifs
Liste des tarifs associés à l'OD.
Detailed Description
Classe représentant un itinéraire Origine-Destination avec des tarifs associés.
Definition at line 12 of file OD.hpp.
Constructor & Destructor Documentation
OD()
OD::OD (const std::string & ori, const std::string & dest)
Constructeur de la classe OD.
Parameters
ori Origine du trajet.
dest Destination du trajet.
Definition at line 7 of file OD.cpp.
    : origine(ori), destination(dest) {}
References destination, and origine.
Member Function Documentation
afficher()
void OD::afficher () const
Affiche la liste des tarifs associés à l'OD pour une meilleur visualisation.
Definition at line 11 of file OD.cpp.
{
    std::cout << "Itinéraire : " << origine << " -> " << destination << std::endl;
    if (tarifs.empty()) {
        std::cout << "Aucun tarif disponible." << std::endl;
    }
    else {
        for (const auto& tarif : tarifs) {
            tarif.afficher();
        }
    }
}
References destination, origine, and tarifs.
ajouterTarif()
void OD::ajouterTarif (const Tarif & tarif)
Ajoute un tarif à la liste en respectant certaines règles :
Si un tarif avec la même classe de réservation existe déjà :
Remplace l’ancien tarif si le nouveau a une valeur Net inférieure.
Si les valeurs Net sont égales, garde celui avec la taxe la plus faible.
Sinon, ajoute simplement le tarif.
Parameters
tarif Objet Tarif à ajouter.
Definition at line 27 of file OD.cpp.
{
    for (auto it = tarifs.begin(); it != tarifs.end(); ++it) {
        if (it->classeReservation == tarif.classeReservation) {
            // Remplacement si la nouvelle valeur Net est inférieure
            if (tarif.getNet() < it->getNet()) {
                *it = tarif;
            }
            // Remplacement si les valeurs Net sont égales mais avec une taxe plus faible
            else if (tarif.getNet() == it->getNet() && tarif.getTaxe() < it->getTaxe()) {
                *it = tarif;
            }
            return; // Fin de la méthode si remplacement effectué
        }
    }
    // Ajout du tarif si aucun remplacement n’a été effectué
    tarifs.push_back(tarif);
}
References Tarif::classeReservation, Tarif::getNet(), Tarif::getTaxe(), and tarifs.
calculerMoyenneNet()
double OD::calculerMoyenneNet () const
Calcule la moyenne des tarifs nets.
Exceptions
std::runtime_error Si aucun tarif n'est disponible.
Returns
Moyenne des tarifs nets.
Definition at line 89 of file OD.cpp.
{
    if (tarifs.empty()) {
        throw std::runtime_error("Aucun tarif disponible.");
    }
    // Somme de toutes les valeurs Net des tarifs
    long somme = std::accumulate(tarifs.begin(), tarifs.end(), 0L,
        [](long acc, const Tarif& tarif) {
            return acc + tarif.getNet();
        });
    // Calcule et retourne de la moyenne
    return static_cast<double>(somme) / tarifs.size();
}
References tarifs.
obtenirTarifNetMaximum()
Tarif OD::obtenirTarifNetMaximum () const
Retourne le tarif net maximum parmi la liste des tarifs.
Exceptions
std::runtime_error Si aucun tarif n'est disponible.
Returns
Tarif ayant la plus grande valeur nette.
Definition at line 70 of file OD.cpp.
{
    if (tarifs.empty()) {
        throw std::runtime_error("Aucun tarif disponible.");
    }
    const Tarif* tarifMax = &tarifs[0];
    // Parcourt tous les tarifs pour trouver celui avec la plus grande valeur Net
    for (const auto& tarif : tarifs) {
        if (tarif.getNet() > tarifMax->getNet()) {
            tarifMax = &tarif;
        }
    }
    return *tarifMax;
}
References Tarif::getNet(), and tarifs.
obtenirTarifNetMinimum()
Tarif OD::obtenirTarifNetMinimum () const
Retourne le tarif net minimum parmi la liste des tarifs.
Exceptions
std::runtime_error Si aucun tarif n'est disponible.
Returns
Tarif ayant la plus petite valeur nette.
Definition at line 51 of file OD.cpp.
{
    if (tarifs.empty()) {
        throw std::runtime_error("Aucun tarif disponible.");
    }
    const Tarif* tarifMin = &tarifs[0]; // Initialise un pointeur vers le premier tarif comme référence de comparaison
    // Parcourt tous les tarifs pour trouver celui avec la plus petite valeur Net
    for (const auto& tarif : tarifs) {
        if (tarif.getNet() < tarifMin->getNet()) {
            tarifMin = &tarif;
        }
    }
    return *tarifMin;
}
References Tarif::getNet(), and tarifs.
Member Data Documentation
destination
std::string OD::destination
Destination du trajet.
Definition at line 15 of file OD.hpp.
origine
std::string OD::origine
Origine du trajet.
Definition at line 14 of file OD.hpp.
tarifs
std::vector<Tarif> OD::tarifs private
Liste des tarifs associés à l'OD.
Definition at line 62 of file OD.hpp.
The documentation for this class was generated from the following files:
include/OD.hpp
src/OD.cpp